---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  # - name: ubuntu-16.04
  #   driver:
  #     customize:
  #       memory: 8192
  #       cpus: 2
  #     network:
  #       - ["forwarded_port", {guest: 8888, host: 8888}]
  #       - ["private_network", {ip: "192.168.33.100"}]
  # - name: centos-7
  #   driver:
  #     customize:
  #       memory: 8192
  #       cpus: 2
  #     network:
  #       - ["forwarded_port", {guest: 8888, host: 8888}]
  #       - ["private_network", {ip: "192.168.33.101"}]
  # - name: debian-9
  #   driver:
  #     box: bento/debian-9
  #     customize:
  #       memory: 8192
  #       cpus: 2
  #     network:
  #       - ["forwarded_port", {guest: 8888, host: 8888}]
  #       - ["private_network", {ip: "192.168.33.102"}]
  - name: rhel7
    driver:
      box: generic/rhel7
      customize:
        memory: 8192
        cpus: 2
      network:
        - ["forwarded_port", {guest: 8888, host: 8888}]
        - ["private_network", {ip: "192.168.33.103"}]

suites:
  - name: default
    run_list:
      - recipe[contrast-teamserver::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
