---
driver:
  name: azurerm
  subscription_id: '4352f0e7-67db-4001-8352-25147175ee02'
  location: 'West US'
  machine_size: 'Standard_DS3_v2'

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  ssh_key: ~/.ssh/id_kitchen_azurerm

platforms:
  # - name: windows2008-r2
  #   driver_config:
  #     image_urn: MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:latest
  #     username: azure
  #     password: Cod3Can!
  #     winrm_powershell_script: |-
  #       winrm quickconfig -q
  #       winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="512"}'
  #       winrm set winrm/config '@{MaxTimeoutms="1800000"}'
  #       winrm set winrm/config/service '@{AllowUnencrypted="true"}'
  #       winrm set winrm/config/service/auth '@{Basic="true"}'
  #   transport:
  #     name: winrm
  #     elevated: true
  # - name: windows2012-r2
  #   driver_config:
  #     image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
  #     username: azure
  #     password: Cod3Can!
  #   transport:
  #     name: winrm
  #     elevated: true
  # - name: windows2016
  #   driver_config:
  #     image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
  #     username: bchau
  #     password: ContrastRocks123!
  #   transport:
  #     name: winrm
  #     elevated: true
  - name: centos-7.5
    driver:
      image_urn: OpenLogic:CentOS:7.5:latest
      vm_name: centos-75-vm
      vm_tags:
        ostype: linux
        distro: centos


suites:
  - name: default
    run_list:
      - recipe[contrast-teamserver-windows::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: